# Generated by Django 3.2.9 on 2021-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=80)),
                ('foto', models.CharField(max_length=30)),
            ],
        ),
    ]
